<?php
$admin_options_defs=array();
$admin_options_defs['Administration']['SuperSweetAdmin']=array(
        'Administration',
        'LBL_SUPERSWEETADMIN_ENTRY_TITLE',
        'LBL_SUPERSWEETADMIN_DESC',
        './index.php?module=Administration&entryPoint=SuperSweetAdmin'
);
$admin_group_header[]=array(
    'LBL_SUPERSWEETADMIN_TITLE',
    '',
    false,
    $admin_options_defs
);
?>